apiVersion: v1
kind: Secret
metadata:
  labels:
    app: django-app
  name: {{ .Values.name }}
stringData:
  {{- if .Values.db.enabled }}
  database-user: {{ .Values.db.user }}
  database-password: {{ .Values.db.password }}
  {{- end }}
  django-secret-key: {{ .Values.django_secret_key }}
