apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: django-app
  name: {{ .Values.name }}
spec:
  ports:
  - name: web
    port: {{ .Values.port }}
    targetPort: {{ .Values.target_port }}
  selector:
    name: {{ .Values.name }}
